%% MassStab.mass.BuildMassObj — Build cast.MassObj compatible array
%  Arm positions mirror BuildGeometry.m / engine.m / landingGear.m exactly

function massObj = BuildMassObj(ADP, CIII)

wg   = MassStab.geom.Wing(ADP);
L_f  = ADP.CockpitLength + ADP.CabinLength + ADP.CabinRadius*1.48;
x_eng = ADP.WingPos - 0.75*wg.MAC;       % engine.m line 27

W_fuel_wing  = 0.667*ADP.MTOM*ADP.Mf_Fuel;
W_fuel_belly = 0.333*ADP.MTOM*ADP.Mf_Fuel;
m_inst = CIII.W_prop/ADP.N_eng - ADP.m_eng_each;

massObj = [ ...
  mk('Wing',          CIII.W_wing,      [ADP.WingPos;                       0]), ...
  mk('Fuselage',      CIII.W_fus,       [L_f/2;                             0]), ...
  mk('Systems',       CIII.W_sys,       [L_f/2;                             0]), ...
  mk('Fuel Systems',  CIII.W_fuelsys,   [L_f/2;                             0]), ...
  mk('HTP',           CIII.W_ht,        [ADP.HtpPos + wg.c_root*0.25;       0]), ...
  mk('VTP',           CIII.W_vt,        [ADP.VtpPos + wg.c_root*0.25;       0]), ...
  mk('Landing Gear',  CIII.W_lg,        [ADP.WingPos + wg.MAC*0.4;          0]), ...
  mk('Engine_R_In',   ADP.m_eng_each,   [x_eng;  0.38*ADP.Span/2]),              ...
  mk('Engine_R_Out',  ADP.m_eng_each,   [x_eng;  0.68*ADP.Span/2]),              ...
  mk('Engine_L_In',   ADP.m_eng_each,   [x_eng; -0.38*ADP.Span/2]),              ...
  mk('Engine_L_Out',  ADP.m_eng_each,   [x_eng; -0.68*ADP.Span/2]),              ...
  mk('Nacelles',      ADP.N_eng*m_inst, [x_eng;                             0]), ...
  mk('Operators',     CIII.W_oper,      [ADP.CockpitLength;                 0]), ...
  mk('Systems_Misc',  CIII.W_ballast,   [ADP.WingPos;                       0]), ...
  mk('Fuel_Wing',     W_fuel_wing,      [ADP.WingPos + wg.MAC*0.15;         0]), ...
  mk('Fuel_Belly',    W_fuel_belly,     [ADP.WingPos + wg.MAC*0.05;         0]), ...
  mk('Payload',       ADP.TLAR.Payload, [ADP.CockpitLength+ADP.CabinLength/2; 0]) ...
];

fprintf('  MassObj: %d components, total = %.1f t\n', ...
    length(massObj), sum([massObj.m])/1e3);
end

function obj = mk(name, mass, X)
    obj.Name=name; obj.m=mass; obj.X=X;
end
